services:
  backend:
    build: ./backend/djrepo
    command: sh -c "python manage.py collectstatic --noinput && gunicorn mysite.wsgi:application --bind 0.0.0.0:8000"
    depends_on:
      - db
      - redis
    environment:
      - DB_HOST=db
      - DB_PASSWORD=secret
    volumes:
      - static_volume:/app/static
    deploy:
      replicas: 3 # Scaling Backend to 3 instances!

  frontend-build:
    build: ./frontend
    command: sh -c "npm run build && cp -r dist/* /shared/"
    volumes:
      - frontend_dist:/app/dist
      - static_volume:/shared

  caddy:
    image: caddy:2-alpine
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - static_volume:/srv # Serve frontend from volume
    depends_on:
      - backend
      - frontend-build

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_PASSWORD=secret
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:alpine

volumes:
  pgdata:
  static_volume:
  frontend_dist:
